name: Check C++ formatting
on: 
  pull_request:
  push:
    branches:
      - master
jobs:
  cpp-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DoozyX/clang-format-lint-action@v0.14
        with:
          clangFormatVersion: 14
